theme: jekyll-theme-midnight
title: Golden Wedding of Black Holes and Thermodynamics
description: An Online Celebration
github:
  is_project_page: false

collections:
  minicourses:
    output: true
    
defaults:
  - scope:
      path: ""
      type: "minicourses"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "calendar"
    values:
      layout: "default"
  - scope:
      path: ""
    values:
      layout: "default"
